name: flutter_semantic_lints_example
description: Example project for flutter_semantic_lints.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.8.1
  flutter_semantic_lints:
    path: ..

flutter:
  uses-material-design: true
