name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install package dependencies
        run: dart pub get

      - name: Analyze package
        run: dart analyze

      - name: Install example dependencies
        working-directory: example
        run: flutter pub get

      - name: Enable custom_lint for example
        working-directory: example
        run: cp analysis_options.custom_lint.yaml analysis_options.yaml

      - name: Run custom_lint integration checks
        working-directory: example
        run: dart run custom_lint
